server:
  port: 19000



spring:
  application:
    name: @artifactId@
    


# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://naza-eureka:18761/eureka/
